namespace CS.CorePlatform
{
	public enum ErrorCode
	{
		LOBBY_CONNECTION_FAILED = 0,
		LOBBY_CREATE_UNSUPPORTED_TYPE = 1,
		LOBBY_CREATE_INVALID = 2,
		LOBBY_CREATE_UNKNOWN = 3,
		LOBBY_JOIN_INVALID = 4,
		LOBBY_JOIN_FULL = 5,
		LOBBY_JOIN_UNKNOWN = 6,
		LOBBY_LOCAL_CONNECTION_FAILED = 7,
		UNKNOWN = 8
	}
}
